name: CI 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # JDK
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'
      # Cache
      - name: Cache maven deps
        uses: actions/setup-java@v4
        env:
          cache-name: cache-maven-deps
        with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-keys: |
          ${{ runner.os }}-maven-
      # Build Maven       
      - name: Build with Maven
        run: mvn -B verify 
